### ISSUE TITLE
tax_version

### ISSUE THREAD

**Issue by luocmin** [mseg-dataset/mseg-semantic#13]
What does tax_version: 4.0 refer to?
![image](https://user-images.githubusercontent.com/57932842/96098462-b66fd400-0f04-11eb-8023-f197a449bb6a.png)

**Comment by johnwlambert** [comment]
Hi @luocmin, thanks for catching that. That parameter was deprecated (no longer required, was used before we converged on our final taxonomy). I've updated the training script to reflect that: https://github.com/mseg-dataset/mseg-semantic/pull/9/commits/81705c168bccbf60d71b184d5b92e3ebd5c10d1d

**Comment by luocmin** [comment]
Regarding tax_version author, you have modified the training script and deleted tax_version in the configuration parameters, but there is still a line in the training script that requires tax_version to judge
![image](https://user-images.githubusercontent.com/57932842/96207906-f1bee100-0f9e-11eb-83a5-1fb375a95289.png)
![image](https://user-images.githubusercontent.com/57932842/96207933-03a08400-0f9f-11eb-8368-725d9cbe68f9.png)

**Comment by johnwlambert** [comment]
Thanks for catching that, should be resolved in the latest commit
