### ISSUE TITLE
mseg-3m-720p.pth?

### ISSUE THREAD

**Issue by RodMech** [mseg-dataset/mseg-semantic#22]
Hi! Thanks for your gorgeous work!
I was wondering if there are no mseg-3m-720p.pth weights in your release files?
Many thanks and congratulations

**Comment by johnwlambert** [comment]
Hi @RodMech, that file is linked from the readme [here](https://github.com/mseg-dataset/mseg-semantic#other-baseline-models-from-our-paper):

https://drive.google.com/file/d/1Y9rHOn_8e_qLuOnl4NeOeueU-MXRi3Ft/view?usp=sharing

**Comment by johnwlambert** [comment]
(rightmost column of table)

**Comment by RodMech** [comment]
@johnwlambert You rock John, thanks.
