### ISSUE TITLE
Training Time Question 

### ISSUE THREAD

**Issue by lxtGH** [mseg-dataset/mseg-semantic#26]
Hi! @johnwlambert Thank you for opensourcing the code. I wonder how long the training time? what are your training settings for each config.

**Comment by johnwlambert** [comment]
Hi @lxtGH, we used 8 Quadro RTX 6000 cards, each w/ 24 GB of RAM, for training. 

The 3 million crop models took ~2-3 weeks to train on such hardware, and the 1 million crop models took ~4-7 days.

**Comment by johnwlambert** [comment]
Closing for now since I haven't heard back, feel free to re-open if you have further questions.

**Comment by lxtGH** [comment]
@johnwlambert Hi!  Which config is the 3 million crop model? and Which config is The 3 million crop models? Could you provide the training commend for reference?
