### ISSUE TITLE
instance annotation provided?

### ISSUE THREAD

**Issue by jinfagang** [mseg-dataset/mseg-semantic#4]
instance annotation provided?

**Comment by liuzhuang13** [comment]
We will release the code and models (based on detectron2) for instance/panoptic segmentation later, hopefully within one month. There our instance annotation is extracted from the relabeled semantic annotation using a script.

**Comment by johnwlambert** [comment]
Thanks for your interest in our work @jinfagang. We don't relabel object boundaries, but rather assign new categories to object instance masks via relabeling. The relabeled instance annotations are available [here](https://github.com/mseg-dataset/mseg-api/tree/master/mseg/relabeled_data). Instructions for downloading the MSeg dataset can be found [here](https://github.com/mseg-dataset/mseg-api/blob/master/download_scripts/README.md).
