### ISSUE TITLE
What are the difference between cvpr paper and your arxiv(PAMI-like) paper?

### ISSUE THREAD

**Issue by lxtGH** [mseg-dataset/mseg-semantic#45]

**Comment by lxtGH** [comment]
Will the panoptic segmentation annotation be released ??

**Comment by johnwlambert** [comment]
Hi @lxtGH, thanks for your interest in our work.

In our [new expanded, journal-length Arxiv paper](https://arxiv.org/pdf/2112.13762.pdf), there are a number of differences vs. our CVPR 2020 paper:

- We evaluate our models in the 2020 Robust Vision Challenge (RVC) as an extreme generalization experiment. MSeg training sets include only three of the seven datasets in the RVC; more importantly, the evaluation taxonomy of RVC is different and more detailed. Surprisingly, our model shows competitive performance and ranks second.

- To evaluate how close we are to the grand aim of robust, efficient, and complete scene understanding, we go beyond semantic segmentation by training instance segmentation and panoptic segmentation models using our dataset.

- Moreover, we also evaluate various engineering design decisions and metrics, including resolution and computational efficiency. (We evaluate runtime of our models, and train & evaluate models at different resolutions for practitioners who have different computational limitations).

There is no separate panoptic segmentation annotation; MSeg's relabeled classes per instance are directly applicable to panoptic segmentation as well.

**Comment by johnwlambert** [comment]
Closing the issue, feel free to re-open if you have further questions @lxtGH
