### ISSUE TITLE
The 'sklearn' PyPI package is deprecated, use 'scikit-learn'

### ISSUE THREAD

**Issue by BonifazStuhr** [mseg-dataset/mseg-semantic#51]
Dear authors,

First of all, thank you very much for your great work! I am happy to use your models in a project of mine. A user of the project has reported an easily fixable problem regarding your requierements.txt here: #https://github.com/BonifazStuhr/feamgan/issues/1#issuecomment-1835648672. 

It says that **"The 'sklearn' PyPI package is deprecated, use 'scikit-learn'"**.   You can therefore simply replace `sklearn` with `scikit-learn` in` requierements.txt`.

I recreated the issue as well. Down below you can see the more detailed error message when installing `mseg-semantic` with `pip install`. 

3.539 Collecting sklearn
3.557   Downloading sklearn-0.0.post11.tar.gz (3.6 kB)
3.724     ERROR: Command errored out with exit status 1:
3.724      command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bfuobfzn/sklearn/setup.py'"'"'; \_\_file\_\_='"'"'/tmp/pip-install-bfuobfzn/sklearn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(\_\_file\_\_);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, \_\_file\_\_, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-bfuobfzn/sklearn/pip-egg-info
3.724          cwd: /tmp/pip-install-bfuobfzn/sklearn/
3.724     Complete output (18 lines):
3.724     The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
3.724     rather than 'sklearn' for pip commands.
3.724     
3.724     Here is how to fix this error in the main use cases:
3.724     - use 'pip install scikit-learn' rather than 'pip install sklearn'
3.724     - replace 'sklearn' by 'scikit-learn' in your pip requirements files
3.724       (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
3.724     - if the 'sklearn' package is used by one of your dependencies,
3.724       it would be great if you take some time to track which package uses
3.724       'sklearn' instead of 'scikit-learn' and report it to their issue tracker
3.724     - as a last resort, set the environment variable
3.724       SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
3.724     
3.724     More information is available at
3.724     https://github.com/scikit-learn/sklearn-pypi-package
3.724     
3.724     If the previous advice does not cover your use case, feel free to report it at
3.724     https://github.com/scikit-learn/sklearn-pypi-package/issues/new
3.724     ----------------------------------------
3.758 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mseg-dataset** [comment]
Thank you @BonifazStuhr, fixed now in https://github.com/mseg-dataset/mseg-semantic/pull/52.
