### ISSUE TITLE
Format of weights

### ISSUE THREAD

**Issue by soumik12345** [mseg-dataset/mseg-semantic#8]
Hi, can you please tell me if the weights include the model structure or it's just the weights? If the last is true then to which model these weights refer to since under the models dir there are several model implementations?

**Comment by johnwlambert** [comment]
Hi @soumik12345 , thanks for your interest in our work.

The pre-trained models follow the HRNet-W48 architecture. The model structure is defined in the code [here](https://github.com/mseg-dataset/mseg-semantic/blob/master/mseg_semantic/model/seg_hrnet.py#L274).

The saved weights provide a dictionary between keys (unique IDs for each weight identifying the corresponding layer) and values (the floating point weights).

**Comment by AvivSham** [comment]
Hi @soumik12345  and @johnwlambert ,
I have another question please, what was the image shape HRNet-W48 model was trained on?

Thank you for helping!

**Comment by johnwlambert** [comment]
Hi @AvivSham, please refer to https://github.com/mseg-dataset/mseg-semantic#experiment-settings.

Images resized to 1080p, then a 713x713 crop is taken for almost all models.
There are only two exceptions: MSeg-3m-480p and  MSeg-3m-720p (resized to 480p or 720p, respectively, before a crop is taken).

**Comment by AvivSham** [comment]
@johnwlambert thank you for the information!
